### ISSUE TITLE
Why implementing costume ` django.contrib.auth.get_user_model().` in utils ? 

### ISSUE THREAD

**Issue by polinom** [szopu/django-rest-registration#10]
Just curious why did you implement this `get_user_model_class` in `utils.py`? 

https://github.com/szopu/django-rest-registration/blob/master/rest_registration/utils.py#L10 ?

When django has the same function available out of the box?

https://docs.djangoproject.com/en/2.0/topics/auth/customizing/#referencing-the-user-model

**Comment by szopu** [comment]
No particular reason; probably because I didn't know about this helper. I see it has nicer error handling. I will refactor the code to use it, not sure if by using it directly in `get_user_model_class` or remove `get_user_model_class` entirely. 
Thanks for sharing the idea!
