### ISSUE TITLE
Documentation on using token for authentication

### ISSUE THREAD

**Issue by PotatoDrug** [szopu/django-rest-registration#13]
I see that we can use token authentication method but there is no documentation on how to switch to token authentication from session authentication.

**Comment by szopu** [comment]
Assuming that `'rest_framework.authtoken'` is already in your `INSTALLED_APPS`, you need to add `'rest_framework.authentication.TokenAuthentication'` to `'DEFAULT_AUTHENTICATION_CLASSES'` in `REST_FRAMEWORK` setting, like shown here:

https://github.com/szopu/django-rest-registration/blob/f7c9bd68c43877d907aeb41cd087bdd2a7c2988c/examples/sharedlinks/sharedlinks-backend/sharedlinks/settings.py#L168-L172

This should cause the login view to return the token in result dict when login is successful.

I think it would be nice to have better documentation than just bare README.md but this may take some time to do.

**Comment by PotatoDrug** [comment]
This worked thanks
