### ISSUE TITLE
Overwrite `LoginSerializer` though settings?

### ISSUE THREAD

**Issue by polinom** [szopu/django-rest-registration#19]
Can overwrite `LoginSerializer` using setting in same way like we can redefine registration and profile serializers?

```
'LOGIN_SERIALIZER_CLASS': 'rest_registration.api.serializers.DefaultLoginUserSerializer',
```

For example `django-rest-auth` has this: `TOKEN_SERIALIZER` setting. 

http://django-rest-auth.readthedocs.io/en/latest/configuration.html

**Comment by szopu** [comment]
Currently this is not possible. We could add that but the problem is that this serializer relies on the `login` field and `password` field being defined in such serializer.

To be sincere, I don't understand why one would need it. Could you provide some use case for that?

**Comment by szopu** [comment]
Looks like GH closed this issue automatically. I added `LOGIN_SERIALIZER_CLASS` which can be replaced by any serializer class as long it has `get_authenticated_user` method for extracting the user matching given credentials to the serializer.

**Comment by polinom** [comment]
Thanks @szopu, it's going to be very helpful.
