### ISSUE TITLE
Question : Registration without password_confirm field

### ISSUE THREAD

**Issue by sks444** [szopu/django-rest-registration#2]
I want to create a registration form without password_confirm field. Is there a way to change the registration api accordingly?

**Comment by szopu** [comment]
Currently the easiest way is to replace the default register serializer with your own in settings:
```python
REST_REGISTRATION = {
    ...
    'REGISTER_SERIALIZER_CLASS': 'myapp.serializers.MyRegisterUserSerializer',
    ...
}
```

The serializer would resemble something like that:

```python
from django.contrib.auth.models import User
from django.contrib.auth.password_validation import validate_password
from rest_framework import serializers
from rest_registration.api.serializers import _build_initial_user


class MyRegisterUserSerializer(serializers.ModelSerializer):

    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'first_name',
            'last_name',
            'password',
        )

    def validate_password(self, password):
        user = _build_initial_user(self.initial_data)
        validate_password(password, user=user)
        return password

    def create(self, validated_data):
        return self.Meta.model.objects.create_user(**validated_data)
```
I didn't test the code above, it may need some refinement. The `User` from `django.contrib.user` can be obviously replaced with the custom `User` model, if you're using one.

I agree, it would be nice to just add simple switch to `REST_REGISTRATION` settings for that. Password confirmation is something which could be validated only on frontend level.

I will create separate issue for that.

**Comment by szopu** [comment]
I added `REGISTER_SERIALIZER_PASSWORD_CONFIRM` field in the `REST_REGISTRATION` settings which is by default `True`, but if you set it to `False` then `password_confirm` is not required (and you don't need to replace the default register serializer).
