### ISSUE TITLE
Make login API compatible with email address

### ISSUE THREAD

**Issue by sks444** [szopu/django-rest-registration#5]
For now, login API is taking two fields i.e. "login" and "password" for logging in a user. How can we make this API compatible with the email address of the user? i.e. a user can log in to the website by entering his username or email address along with the password.

**Comment by szopu** [comment]
If you want to use either username or email as login when performing login you can set it in `REST_REGISTRATION` settings:
```python
REST_REGISTRATION = {

    ...

    'USER_LOGIN_FIELDS': ['username', 'email'],
    ...

}
```

or even better if you have your own user class you could set `LOGIN_FIELDS` there.

```python
class MyUser(AbstractUser):

    ...
    LOGIN_FIELDS = ['username', 'email']
    ...
```

**Comment by szopu** [comment]
I assume the comment above helped. If not, please inform me about that. Otherwise I will close this issue due to lack of activity.

**Comment by sks444** [comment]
Yes, it helped. Thank you :)
I am closing the issue.

**Comment by mynksngh** [comment]
/api/v1/accounts/login/
Post This Data:
{
"email": "demo",
"password": "123456"
}

Getting Error:

{
    "login": [
        "This field is required."
    ]
}


My Setting:

'USER_LOGIN_FIELDS': ['username', 'email'],

**Comment by apragacz** [comment]
@mynksngh You are using `email` field instead of `login` field in your request. You should use `login` field. If you want to use `email` field specifically for some reason you can provide you own LoginSerializer like described here: https://github.com/apragacz/django-rest-registration/issues/19#issuecomment-381758979
