### ISSUE TITLE
Email verification views with get method

### ISSUE THREAD

**Issue by EmilioK97** [szopu/django-rest-registration#6]
Currently I assume we must implement the view that we specify in the REGISTER_EMAIL_VERIFICATION_URL value. Because I only found the implementation of the POST version of it (verify_email in register_email.py) and the link send to the email is a get of course. Is this right or its already implemented?

**Comment by szopu** [comment]
That is correct, you should implement your own URL handler on your frontend application and plug it into `REGISTER_EMAIL_VERIFICATION_URL`. The frontend will receive some parameters in HTTP GET query. Then it should perform AJAX HTTP POST with these parameters passed as POST data to `verify-email/` REST API endpoint (this is the one you found) and display some success / failure message to the user depending on the response. In case of email verification the parameters (passed as HTTP GET query params) are:
* `user_id`
* `email`
* `timestamp`
* `signature`

(you can find them in `VerifyEmailSerializer`).

You can see how it is tested here, maybe this will clear something up:

https://github.com/szopu/django-rest-registration/blob/master/tests/api/test_register_email.py

Hope that helps.

PS: If you don't want to have separate frontend application (e.g. written in Angular/React/Vue/...) and write everything as Django views which will generate HTML pages, I would recommend using `django-registration` package instead.

**Comment by EmilioK97** [comment]
Ok, Thanks!
